runmode: debug               # 开发模式, debug, release, test
addr: :8000                  # HTTP绑定端口
name: apiserver              # API Server的名字
url: http://127.0.0.1:8000   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数
gormlog: true

jwt_secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5

tls:
  addr: :8001
  cert: conf/server.crt
  key: conf/server.key

log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/apiserver.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7

db:
  name: test
  addr: 192.168.241.145:3306
  username: remote
  password: 123456


docker_db:
  name: test
  addr: 192.168.241.145:3306
  username: remote
  password: 123456